version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: użytkownik
      POSTGRES_PASSWORD: hasło
      POSTGRES_DB: baza_danych
    volumes:
      - db_dane:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_dane:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://użytkownik:hasło@db:5432/baza_danych
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: klucz_sekretny_jwt_bardzo_dlugi_i_losowy
      PERPLEXITY_COOKIE: ciasteczko_perplexity_ai_wymagane
      LOG_LEVEL: INFO
      # PERPLEXITY_CONFIG_PATH: /app/config.yaml # Jeśli chcesz używać pliku zamiast zmiennych env
    volumes:
      - backend_dane:/app/data # Na sesje, logi itp.
      # - ../config.yaml:/app/config.yaml # Mapowanie zewnętrznego pliku konfiguracyjnego
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - frontend_dane:/app/build
    # Frontend będzie serwowany przez Nginx w produkcji, port tylko dla developmentu
    # ports:
    #   - "3000:80"

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dane:/usr/share/nginx/html:ro # Serwowanie plików frontend
      - backend_dane/logs:/var/log/nginx # Opcjonalnie logi nginx do tego samego wolumenu
    ports:
      - "80:80"
      - "443:443" # Dla HTTPS
    depends_on:
      - backend
      - frontend # Upewnij się, że frontend zbudował swoje pliki

volumes:
  db_dane:
  redis_dane:
  backend_dane:
  frontend_dane:
